name: tree_circle_progress_example
description: Example app demonstrating tree_circle_progress package
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  tree_circle_progress:
    git:
      url: https://github.com/ritz-dev/tree_circle_progress.git
      ref: tree_circle_progress

  tree_assets:
    git:
      url: https://github.com/ritz-dev/tree_circle_progress.git
      ref: tree_circle_progress
      path: packages/tree_assets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true