name: tree_assets
description: Tree assets for tree_circle_progress widget
version: 1.0.0

environment:
  sdk: ^3.9.0

flutter:
  assets:
    - assets/logo/tree_0.png
    - assets/logo/tree_1.png
    - assets/logo/tree_2.png
    - assets/logo/tree_3.png
    - assets/logo/tree_4.png
    - assets/logo/tree_5.png
    - assets/logo/tree_6.png
    - assets/logo/tree_7.png
    - assets/logo/tree_8.png
    - assets/logo/tree_9.png
    - assets/logo/tree_10.png
    - assets/logo/tree_11.png
    - assets/logo/tree_12.png
    - assets/logo/tree_13.png
    - assets/logo/tree_14.png
    - assets/logo/tree_15.png
    - assets/logo/tree_16.png
    - assets/logo/tree_17.png
    - assets/logo/tree_18.png
    - assets/logo/tree_19.png